### ISSUE TITLE
Markers

### ISSUE THREAD

**Issue by AleCaram** [cadetill/gmlib_v2#10]
First of all, congratulations to you on this excellent job. If I can help in help in any way just let me know. I am very thankful for gmlib_v1 and for this follow-up.

I have just successfully reinstalled all installation packages of gmlib_v2 project on Delphi 10.4. A TGMMapChrm component was created, but no Marker Component was created. In addition, when the MarkerChromium example is running I can not see any Marker on the map although it is possible to check that they are being created and deleted successfully.

Was I expected to have other behavior so far?

Best regards,

Alexandre

**Comment by cadetill** [comment]
Hi Alenxander 

Now I am working on the markers. The master branch is a development branch, for this reason you may find unexpected bugs and errors.

You can find the closed versions into the [releases](https://github.com/cadetill/gmlib_v2/releases) area and you can see into the Readme file what is coded (on release packages), what I'm coding and the road map

Thanks for using GMLib
