### ISSUE TITLE
Error 2613

### ISSUE THREAD

**Issue by OswaldoSoftw** [cadetill/gmlib_v2#12]
Hola buen día, desde hace muchos años he utilizado la libreria gmlib 1 en delphi 7, pero lamentablemente actualmente hay un problema con los MARKERS que no tengo idea por que no aparecen graficamente, y bien trato de mudarme a GMlib 2 con alejandria 11, pero me marca un error  [dcc32 Fatal Error] UMainFrm.pas(8): F2613 Unit 'GMLib.Classes' not found. , disculpa mi nivel de ignorancia pero no se como solucionarlo, Agradezco el tiempo invertido en mi post, Gracias.

**Comment by cadetill** [comment]
Hola. La gestión de marcadores todavía no está terminada, de ahí que te dé errores. Los fuentes que están en el repositorio pueden contener fallos o directamente no compilar. Los "buenos" son los que están empaquetados en las releases
