### ISSUE TITLE
Issues for missing components

### ISSUE THREAD

**Issue by marGEOcus** [cadetill/gmlib_v2#7]
I can imagine that you are annoying about the questions about missing components, but especially now that v1 no longer works, there are definitely some who want to know how and when the v2 continues.
We are all very grateful for you to continue your project. Perhaps it would help if you open issues for every not yet implemented function so that everyone can see what is still planned. 

Then I could also save myself the following question: will be there also support for OSM?  ;-)

Thank you for your great work!

**Comment by cadetill** [comment]
Hi

No worries to ask about GMLib v2 TO DO list, I'm happy to know that there are people to use it.

About this TO DO list, you need to know that my idea is to implement all functionalities from Google Maps API. And about OSM.... I dont know yet, perhaps I will do, but not sure :-)

I will put on readme the GMLib road map ;-)
